[build-system]
requires = [
    "setuptools>=61",
    "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fms-hf-tuning"
version = "0.0.1"
description = "FMS HF Tuning"
authors = [
  {name = "Sukriti Sharma", email = "sukriti.sharma4@ibm.com"},
  {name = "Anh Uong", email = "anh.uong@ibm.com"},
  {name = "Alex Brooks", email = "Alex.Brooks@ibm.com"},
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = "~=3.9"
keywords = ['fms-hf-tuning', 'python', 'tuning']
classifiers=[
    "License :: OSI Approved :: Apache Software License"
]
dependencies = [
    "numpy==1.26.4",
    "accelerate==0.27.2",
    "packaging==23.2",
    "transformers==4.37.2",
    "torch==2.2.1",
    "aim==3.17.5",
    "sentencepiece==0.2.0",
    "tokenizers==0.15.2",
    "tqdm==4.66.2",
    "trl==0.7.11",
    "ninja==1.11.1.1",
    "peft==0.9.0",
    "datasets==2.18.0",
    "fire==0.5.0",
]

[project.optional-dependencies]
flashattention = [
    "wheel==0.42.0",
    "flash-attn",
]

[project.urls]
Homepage = "https://github.com/foundation-model-stack/fms-hf-tuning"
Repository = "https://github.com/foundation-model-stack/fms-hf-tuning"
Issues = "https://github.com/foundation-model-stack/fms-hf-tuning/issues"
